FROM node:18.16-alpine AS build
WORKDIR /app
ADD package*.json ./
ADD /prisma ./prisma/
RUN npm install && npx prisma generate
ADD . .
RUN npm run build

FROM node:18.16-alpine AS production
WORKDIR /app
ADD package*.json ./
RUN npm install --only=prod --ignore-scripts
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /app/dist ./dist
COPY --from=build /app/environment ./environment
COPY --from=build /app/prisma ./prisma
CMD ["npm", "run", "start:prod"]